Resolve todo item bug
upnotes-io/react-todo pull request #53
Opened 2023-04-27 15:35 UTC by gkasoff

Add new todo item on pressing enter in between todo list rows (https://github.com/upnotes-io/react-todo/issues/24#top)

2023-05-07 03:21 UTC, kamalkishor1991 requested changes
@gkasoff thanks a lot for the pull request. 
sorry for the delay in reviewing this. I have added few minor comments. Please take a look.

2023-05-07 03:21 UTC, kamalkishor1991 commented on package-lock.json
Please pull latest master. I have remove this file in master.

2023-05-07 03:21 UTC, kamalkishor1991 commented on src/components/Todo/common/Todo/CompletedList/index.tsx
> +            console.log("completed list changed?");
please remove

2023-05-16 16:06 UTC, gkasoff commented on src/components/Todo/common/Todo/CompletedList/index.tsx
> +            console.log("completed list changed?");
done

2023-05-16 16:06 UTC, gkasoff commented on package-lock.json
done

2023-05-16 16:57 UTC, kamalkishor1991 commented on yarn.lock
please revert this. There should not be any changes in this file

2023-05-16 17:34 UTC, gkasoff commented on package-lock.json
sorry about that - file has been removed

2023-05-24 00:13 UTC, gkasoff commented
@kamalkishor1991 hi is this all good now?

2023-05-24 12:52 UTC, kamalkishor1991 approved these changes

2023-05-24 12:52 UTC, kamalkishor1991 commented on src/components/Todo/Todo.tsx
> +import { isReturnStatement } from "@babel/types";
please remove

2023-05-24 12:53 UTC, merged