Feature/undo redo
upnotes-io/react-todo pull request #56
Opened 2023-05-19 11:19 UTC by shahanahmed86

- listening to key-down events that'll trigger the undo or redo functionality.
- worked on some optimization like using memo/callback where needed.
- made update/remove callback on the Todo component and remove from deep down the tree to implement the undo/redo functionality

2023-05-20 18:04 UTC, kamalkishor1991 commented
@shahanahmed86 thanks a lot for the pull request. I will review it in few days.

2023-05-20 18:15 UTC, shahanahmed86 commented
> @shahanahmed86 thanks a lot for the pull request. I will review it in few days.

This is my first contribution to the open-source community and I am not an expert on team collaboration and GITOPS things. I found anything that I need to work on then please suggest me.

2023-05-21 13:54 UTC, kamalkishor1991 requested changes

2023-05-21 20:50 UTC, shahanahmed86 commented on src/components/Todo/Todo.tsx
> +      if (repeat || !ctrlKey) return;
I have visited the shared [link](https://stackoverflow.com/questions/13319723/listen-to-undo-redo-event-in-contenteditable-div) but the [InputEvent](https://w3c.github.io/input-events/#interface-InputEvent-Attributes) was not properly working with react, it triggers the callback _too many times_ on a single key press. Instead, I've done my research on the `KeyboardEvent` and found that the `metaKey` `boolean` property gets true when next to the spacebar:
- [x] <kbd>Command</kbd> is pressed on Macbook
- [x] <kbd>Window</kbd> is pressed on Linux/Windows
And I've tested it on Macbook it works like a charm. I have updated this pull request also

2023-05-22 12:24 UTC, shahanahmed86 commented on src/components/Todo/Todo.tsx
> +      if (repeat || !ctrlKey) return;
@kamalkishor1991 but the problem is that <kbd>⌘y</kbd> is pressed it also opens the browser history and this is the browser behavior.

2023-05-22 15:35 UTC, kamalkishor1991 commented on src/components/Todo/Todo.tsx
> +      if (repeat || !ctrlKey) return;
@shahanahmed86 I think you should call `event.preventDefault();`
I tried google keep and it is able to handle cmd + y without opening browser history.

2023-05-22 15:41 UTC, kamalkishor1991 requested changes

2023-05-22 16:13 UTC, shahanahmed86 commented on src/components/Todo/Todo.tsx
> +      if (repeat || !ctrlKey) return;
@kamalkishor1991, I've updated the pull request

2023-05-22 16:45 UTC, shahanahmed86 commented on src/components/Todo/common/Todo/Form/index.tsx
> +                <UndoIcon onClick={onUndo} className={classes.iconStyle} />
got it

2023-05-23 14:41 UTC, kamalkishor1991 commented on src/components/Todo/common/Todo/Form/index.tsx
> +                <UndoIcon onClick={onUndo} className={classes.iconStyle} />
No not this header. this is storybook header. I meant that we can introduce a action bar on top of input box and add the icons in the action bar.

2023-05-24 21:32 UTC, shahanahmed86 commented on src/components/Todo/common/Todo/Form/index.tsx
> +                <UndoIcon onClick={onUndo} className={classes.iconStyle} />
I've updated the pull request with toolbar shortcut implementation

2023-05-24 22:25 UTC, shahanahmed86 commented on src/components/Todo/common/Todo/Form/index.tsx
> +                <UndoIcon onClick={onUndo} className={classes.iconStyle} />
@kamalkishor1991 I've found some conflicts with the master that I was trying to merge. I assume resolving conflicts is, for the person, who creates/updates the pull request. So I am working on that.

2023-05-25 17:36 UTC, kamalkishor1991 commented on src/components/Todo/common/Todo/Form/index.tsx
> +                <UndoIcon onClick={onUndo} className={classes.iconStyle} />
yes I merged one PR( #53) yesterday. You can also take a look at the PR to resolve the conflicts correctly.

2023-05-28 00:10 UTC, shahanahmed86 commented
@kamalkishor1991, I've updated the pull request with all conflicts resolved and deployed the app on this [URL](https://shahanahmed86.github.io/react-todo). Please check the demo also before merging.

2023-05-28 08:15 UTC, kamalkishor1991 commented
I found 2 issues.
1. The action bar width should match 
<img width="1212" alt="Screenshot 2023-05-28 at 1 44 41 PM" src="https://github.com/upnotes-io/react-todo/assets/5221843/85f03d80-19e6-4acb-9748-f2d2af9239ab">
the bottom area
2. When adding more items the add item is merging with action bar.
Please check

2023-05-28 19:07 UTC, shahanahmed86 commented
@kamalkishor1991, The changes that you ask to fix are now updated in the last commit:

- making toolbar width according to the Todo component.
- when adding more items the text field is merging in the toolbar.

2023-05-29 16:29 UTC, kamalkishor1991 approved these changes

2023-05-29 16:29 UTC, merged